### ISSUE TITLE
3rd option to replace "The Fence"

### ISSUE THREAD

**Issue by sdelaplain** [jakewhlr/Trial-Meter-Bot#19]
If provided with a 3rd option on setup, replace "The Fence" with that input.
Example:
@TrialMonkey !new_trial OptionA OptionB works as it currently does:  
(Option A - The Fence - Option B)

@TrialMonkey !new_trial OptionA OptionB OptionC puts Option C in place of The Fence 
(Option A - Option C - Option B)

**Comment by jakewhlr** [comment]
Implemented in https://github.com/jakewhlr/trial-monkey/commit/fb511676c37ad96151c9d74fc53a71b05dd50699
